const problemMap = ['今日やること', '制作途中の状態', 'AIへ任せる作業', '再開地点'];
const workflow = ['OBSERVE', 'DECIDE', 'DESIGN', 'BUILD', 'QA', 'RECORD'];
const outcomes = ['課題定義', '情報設計', 'UI / UX', '実装', '独立QA'];

function Section({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) {
  return <section className="rounded-[32px] border border-[#dbe8f2] bg-white p-6 shadow-soft sm:p-12"><p className="text-xs font-medium tracking-[0.08em] text-[#296eab]">{eyebrow}</p><h2 className="mt-4 font-mincho text-2xl font-semibold leading-snug text-ink sm:text-[38px]">{title}</h2>{children}</section>
}

export default function CaseStudy() {
  return <main className="bg-[#f6fafc] px-4 py-10 sm:px-8 sm:py-16 lg:px-12"><div className="mx-auto flex max-w-[1200px] flex-col gap-10 sm:gap-16">
    <section className="rounded-[32px] border border-[#dbe8f2] bg-white p-6 shadow-soft sm:p-12"><p className="text-sm font-medium tracking-[0.08em] text-[#296eab]">SHIZUKU STUDIO / CASE STUDY</p><h1 className="mt-4 font-mincho text-4xl font-semibold leading-tight text-ink sm:text-[64px]">Shizuku OS Dashboard</h1><p className="mt-5 max-w-4xl text-lg leading-relaxed text-neutral2-500 sm:text-[26px]">AIと一人で制作するときの「判断・再開・優先順位」を、1画面に整理する個人向け制作OS。</p><div className="mt-6 flex flex-wrap gap-3">{['React','TypeScript','Tailwind CSS','Vite','Vercel'].map(x => <span key={x} className="rounded-full bg-[#edf7ff] px-4 py-2 text-sm font-medium text-[#296eab]">{x}</span>)}</div></section>
    <Section eyebrow="01 Challenge" title="問題は「情報不足」ではなく、情報が多すぎて次の1手が見えなくなること。"><p className="mt-5 max-w-4xl text-base leading-relaxed text-neutral2-500 sm:text-lg">AIを使った制作では、アイデア・参考情報・途中判断が短時間で増えます。複数の場所に分散すると、制作より先に「今どこまで進めたか」を思い出すコストが発生します。</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{problemMap.map((x,i) => <div key={x} className="rounded-[20px] bg-[#f2faff] p-5"><p className="text-xs text-[#296eab]">0{i+1}</p><p className="mt-3 font-medium text-ink">{x}</p></div>)}</div></Section>
    <Section eyebrow="02 Human × AI Workflow" title="AIは万能役ではなく、工程ごとに役割を分ける。"><p className="mt-5 max-w-4xl text-base leading-relaxed text-neutral2-500 sm:text-lg">調査・要件整理・UI設計・実装・レビュー・記録を分離し、人間側には「採用」「作らない」「完成条件」の判断を残します。</p><div className="mt-7 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{workflow.map(x => <div key={x} className="rounded-[18px] border border-[#d1e3f0] bg-[#f2faff] px-4 py-5 text-sm font-medium text-[#296eab]">{x}</div>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-3">{[['NOW','今やる1本'],['NEXT','次に進める'],['BACKLOG','新案を隔離']].map(([a,b]) => <div key={a} className="rounded-[18px] border border-[#d1e3f0] p-5"><p className="text-sm text-[#296eab]">{a}</p><p className="mt-2 font-medium text-ink">{b}</p></div>)}</div></Section>
    <Section eyebrow="03 Quality Gate" title="生成する工程と、決定する工程を分離する。"><p className="mt-5 max-w-4xl text-base leading-relaxed text-neutral2-500 sm:text-lg">AIは判断材料を増やす。最終的な採否は、人間が目的・文脈・美学を踏まえて決定します。</p><div className="mt-7 grid gap-4 sm:grid-cols-3">{[['採用','目的と完成条件に合う'],['保留','価値はあるが今ではない'],['捨てる','目的から外れる']].map(([a,b]) => <div key={a} className="rounded-[22px] border border-[#d1e3f0] bg-[#f2faff] p-6"><p className="text-2xl font-semibold text-ink">{a}</p><p className="mt-3 text-sm text-neutral2-500">{b}</p></div>)}</div><p className="mt-5 rounded-[18px] bg-[#ebf6ff] px-6 py-5 text-[#296eab]">AI = 候補を作る ／ Human = 文脈を理解して最終判断する</p><img className="mt-5 w-full max-w-[520px] rounded-[24px] border border-[#d1e3f0] object-cover" src="./docs/images/screenshot-quality-gate.png" alt="Quality Gateの実画面" /></Section>
    <Section eyebrow="04 Implementation + QA" title="小さく成立させ、壊れやすい部分を独立QAする。"><p className="mt-5 max-w-4xl text-base leading-relaxed text-neutral2-500 sm:text-lg">localStorage + JSON export / importで核となる体験を先に成立。外部API・ログイン・本格DB・複雑な自動化は初期スコープから外しました。</p><div className="mt-7 grid gap-5 sm:grid-cols-2">{[['IMPLEMENTATION',['React / TypeScript','Tailwind CSS / Vite','localStorage','JSON export / import']],['QA',['保存・読み込み失敗','不正JSON / URL欠損','320px responsive','keyboard / reduced motion','build / typecheck / lint / test']]].map(([title,items]) => <div key={title as string} className="rounded-[22px] border border-[#d1e3f0] bg-[#f2faff] p-6"><p className="text-sm text-[#296eab]">{title as string}</p><ul className="mt-4 space-y-3 text-sm text-ink">{(items as string[]).map(x => <li key={x}>• {x}</li>)}</ul></div>)}</div><div className="mt-6 flex flex-wrap gap-3">{['Figma','Claude Code','Codex QA','Fix','Re-check'].map(x => <span key={x} className="rounded-full border border-[#d1e3f0] px-5 py-3 text-sm text-[#296eab]">{x}</span>)}</div><div className="mt-6 grid gap-5 sm:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]"><img className="w-full rounded-[24px] border border-[#d1e3f0] object-cover" src="./docs/images/screenshot-dashboard-desktop.png" alt="Desktop Dashboardの実画面" /><img className="mx-auto h-full max-h-[560px] rounded-[24px] border border-[#d1e3f0] object-cover" src="./docs/images/screenshot-dashboard-mobile.png" alt="Mobile Dashboardの実画面" /></div></Section>
    <Section eyebrow="05 Result" title="「考える → 選ぶ → 作る → 中断する → 戻る → 完成させる」を支える制作OSへ。"><p className="mt-5 max-w-4xl text-base leading-relaxed text-neutral2-500 sm:text-lg">完成画面だけではなく、制作プロセスそのものを構造化。AIを多く使うからこそ「AIに何を任せ、人間が何を決め続けるか」を設計しました。</p><a href="https://shizuku-os-dashboard.vercel.app/" target="_blank" rel="noreferrer" className="mt-7 block rounded-[22px] bg-[#ebf6ff] p-6"><p className="text-xs text-[#296eab]">LIVE PRODUCT</p><p className="mt-2 font-semibold text-ink">shizuku-os-dashboard.vercel.app</p><p className="mt-2 text-sm text-neutral2-500">公開中の実装をケーススタディの証拠として接続</p></a><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-5">{outcomes.map((x,i) => <div key={x} className="rounded-[18px] border border-[#d1e3f0] bg-[#f2faff] p-4"><p className="text-xs text-[#296eab]">0{i+1}</p><p className="mt-2 text-sm font-medium text-ink">{x}</p></div>)}</div><div className="mt-6 rounded-[22px] bg-[#172b3d] p-7"><p className="text-sm text-[#8fc7f2]">Complexity, quietly structured.</p><p className="mt-2 font-mincho text-2xl font-semibold text-white">複雑なものを、静かに、わかる形へ。</p></div></Section>
    <a href="#/" className="self-start text-sm text-[#296eab]">← Shizuku OSについて戻る</a>
  </div></main>
}
